language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "dinosaurs-shop-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: radiant-caverns-64962
  api_key:
    secure: "rHU4HBQDw3UmgH5k3an/MRjjfh9czpilsyV8G3cKbFD1C9W5u//46tZjC2EWtFgejcb9Nu4f1mUA3CIu5o8rM5+/+DjWKToI2hNpBpi8rDDw19WwnUFKmHv7VV0d3cxRLyKrLNXEKo8WPtXPGnH3Cs0z6VjgPvJ5mxNSekRw54qcxmbUXstMdqQ53XtQfHHAC2P+fRz6wVQW35sualQCQcwzjFSWJAn5EJaFLMeOrIDvGkHyAIhkc3Mx7qQxAKhhgj4CwGrquqQdTzjq9LmE+owyCTsSvoYpvihAdyCYr3VhcXHAbNqUdyR0OppVV9OeqslyiYxsx9lAAOF22Sfr70Ue/kXlup2cyLzcSv4Cv5jP+HCbk697XegZr3TuZ7Ci+3uMFJLyF0Y5ibbcbTMn4EUgFvdk4/32lXSxYBuKeUzp1fcue/1Qg+lCLZn4veM31MJ+BGNDKfn/hr9xIU30YgbsPFDJQrfjAXIDU3NsZbGXkL925VIBUVD0xlelhRHV0eTegy0yaRCfWIetZ1h4LIwOGGHYBwNJa7vTc6Vo/WXplFe+nV76tB+rsEglwi3Br3nB7QChL0Id5g0P2PGquhmDgcASiF5x2MD7xBsM49TFTOVPbq2sBMxQgB6OVbktfaQhhWICLXRz99ZcpNJtOIDqeemnzfZV61+1vsXTZtw="

